version: '3'

services:
  web:
    build: .
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --reload"
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8000}

# Remove the db service since we're using an external database
