version: '3'

services:
  web:
    build: .
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --reload"
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8000}
      - DATABASE_URL=postgresql://tournament_framework_tdxm_user:Ox4fJoKj9v0OL7G2xSMchHXx2PaA4VA6@dpg-csclf49u0jms73fduueg-a.frankfurt-postgres.render.com/tournament_framework_tdxm
