version: '3'

services:
  web:
    build: .
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port $PORT --reload"
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "$PORT:$PORT"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=tournament_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
