services:
  - type: web
    name: tournament-tracker
    env: docker
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: DATABASE_URL
        value: postgresql://tournament_tracker_db_user:ChxzjrD11rVFhray9qeIe3APy8VTBiiy@dpg-crvt0hhu0jms73dtmnlg-a.frankfurt-postgres.render.com/tournament_tracker_db
      - key: PORT
        value: 8000

# Remove the databases section since we're using an external database