services:
  - type: web
    name: tournament-tracker
    env: docker
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tournament-tracker-db
          property: connectionString

databases:
  - name: tournament-tracker-db
    databaseName: tournament_tracker
    user: tournament_tracker