"""add is_third_place to match

Revision ID: c9d1e00fe37d
Revises: f55676af8762
Create Date: 2024-10-24 10:12:13.902473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d1e00fe37d'
down_revision: Union[str, None] = 'f55676af8762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('is_third_place', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'is_third_place')
    # ### end Alembic commands ###
