"""rename_round_number_column

Revision ID: f94904a9a3d9
Revises: d71cdefa5192
Create Date: 2024-10-23 22:23:01.778191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94904a9a3d9'
down_revision = 'd71cdefa5192'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
